In [2]:
!pip install tensorflow

In [34]:
import tensorflow as tf

In [35]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels),(test_images, test_labels)= mnist.load_data()



In [36]:
train_images.ndim

3

In [37]:
train_images[0].ndim

2

In [38]:
from PIL import Image

In [8]:
im = Image.fromarray(train_images[0])
im

In [56]:
# from tensorflow.keras
# from tensorflow.keras import layers
# model = keras.Sequential([
#                             layers.dense(512, activation="relu"),
#                             layers.dense(512, activation="softmax")
#                          ])

SyntaxError: invalid syntax (479609846.py, line 1)

In [41]:
# train_images[0]
train_labels[0]

5

In [42]:
train_images[0].shape

(28, 28)

In [43]:
train_images[0].ndim

2

In [45]:
im= Image.fromarray(train_images[0])
im

In [12]:
from tensorflow.kerast
from tensorflow.keras import layers
model = keras.Sequential([
                            layers.dense(512, activation="relu"),
                            layers.dense(512, activation="softmax")
                         ])

SyntaxError: invalid syntax (2477147575.py, line 1)

In [65]:
>>> train_images.shape
(60000, 28, 28)
>>> len(train_labels)
60000
>>> train_labels
array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

# And here’s the test data:
>>> test_images.shape
(10000, 28, 28)
>>> len(test_labels)
10000
>>> test_labels
array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

NameError: name 'array' is not defined

In [46]:
from tensorflow.keras import models
from tensorflow.keras import layers
model = keras.Sequential()
model.add(layers.Dense(512, activation="relu", input_shape=(28 *28,))),
model.add(layers.Dense(10, activation='softmax'))
                        

NameError: name 'keras' is not defined

In [28]:
import numpy as np
np.array([1,2,4]).shape

(3,)

In [30]:
model

In [34]:
model.compile(optimizer="rmsprop", loss="sparse_categorical_crossentropy",metrics=['accuracy'])

In [38]:
train_images=train_images.reshape((60000,28*28))
train_images=train_images.astype('float32')/255
test_images=test_images.reshape((10000, 784))
test_images=test_images.astype('float32')/255

In [36]:
np.arange(64).reshape(8,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [39]:
train_images.shape

(60000, 784)

In [40]:
model.fit(train_images,train_labels,epochs=5, batch_size=256)

Epoch 1/5
235/235 [==============================] - 2s 6ms/step - loss: 0.3210 - accuracy: 0.9095
Epoch 2/5
235/235 [==============================] - 1s 6ms/step - loss: 0.1366 - accuracy: 0.9609
Epoch 3/5
235/235 [==============================] - 1s 6ms/step - loss: 0.0914 - accuracy: 0.9740
Epoch 4/5
235/235 [==============================] - 1s 6ms/step - loss: 0.0679 - accuracy: 0.9808
Epoch 5/5
235/235 [==============================] - 1s 6ms/step - loss: 0.0525 - accuracy: 0.9846


In [47]:
test_digits =test_images[0:10]
model.predict(test_digits[[0]])


1/1 [==============================] - 0s 19ms/step


array([[1.8072813e-08, 5.3389817e-09, 6.7825972e-06, 2.2321085e-05,
        6.2106303e-10, 1.8666290e-08, 5.1536809e-12, 9.9996972e-01,
        1.4007544e-07, 1.0865525e-06]], dtype=float32)

In [ ]:
predictions=model.predict(test_digits)

In [ ]:
np.argmax(model.predict(test_digits))

In [45]:
predictions

array([[1.8072813e-08, 5.3389919e-09, 6.7825908e-06, 2.2321085e-05,
        6.2106303e-10, 1.8666290e-08, 5.1536809e-12, 9.9996972e-01,
        1.4007557e-07, 1.0865525e-06],
       [5.9719042e-08, 1.8855022e-05, 9.9993372e-01, 3.6126577e-05,
        5.3614627e-13, 2.0042289e-06, 1.3501484e-07, 2.4226674e-11,
        9.0654275e-06, 1.7195282e-11],
       [1.1825904e-05, 9.9650663e-01, 5.0803588e-04, 3.8009486e-05,
        1.6221426e-04, 4.2312364e-05, 1.2635718e-04, 1.9214277e-03,
        6.7457784e-04, 8.5568463e-06],
       [9.9991083e-01, 1.4613636e-08, 6.1900755e-05, 6.8521484e-07,
        2.4729752e-07, 6.1935594e-07, 1.0406548e-05, 9.8377732e-06,
        2.9188010e-08, 5.3901617e-06],
       [3.1350217e-05, 5.4851565e-08, 2.0894684e-05, 3.6220271e-07,
        9.9232626e-01, 1.1262000e-06, 3.9394650e-05, 3.0193623e-04,
        2.1332209e-05, 7.2572795e-03],
       [6.6161954e-07, 9.9660265e-01, 9.9392537e-06, 3.1277430e-06,
        6.4788968e-05, 3.7101813e-07, 1.0461162e-06, 3.26

In [ ]:
test_loss,test_acc=model.evaluate(test_images, test_labels)

In [30]:
from PIL import Image

In [26]:
import numpy as np

AttributeError: shape

In [16]:
four=Image.open("four.jpg")

In [17]:
image=four.convert('L')

In [19]:
image.save("greyscale_four.jpg")

In [27]:
four_grey =Image.open('greyscale_four.jpg')
arr = np.asarray(four_grey)

In [32]:
arr300 = arr.reshape(1,300)

ValueError: cannot reshape array of size 9108 into shape (1,300)