# Learning Numpy and pandas for Data analysis
deal only numeric values
Super fast Processing
Structure = Numpy array 

In [ ]:
Numpy-numerical python

# Creating a numpy Array
1- diemnsional Array

In [173]:
import numpy as np

In [175]:
# using python list
lst=[1,2,3,4,5,6,7,8,9,10]
arr1d = np.array(lst)
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
# using python list
lst=[1,2,3,4,5,6,7,8,9,10]
print(type(lst))
arr1d = np.array(lst)
type(arr1d)

<class 'list'>


numpy.ndarray

In [9]:
len(arr1d)

10

In [10]:
lst[2]

3

In [14]:
lst[-1] =10

In [15]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [17]:
lst*2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [19]:
for a in lst:
    print (a*2)

2
4
6
8
10
12
14
16
18
20


In [21]:
double= []
for a in lst:
    print (a*2)
    double.append(a*2)
    double

2
4
6
8
10
12
14
16
18
20


# vectorized operation

In [22]:
arr1d*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [23]:
arr1d*10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [24]:
arr1d.size

10

In [26]:
arr1d.ndim

1

In [31]:
arr1d.shape

(10,)

In [32]:
arr1d.shape
type(arr1d.shape)

tuple

In [36]:
# using numpy arange
arr1d=np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 2D array 

In [40]:
# 2d array from python list
lst2d=[[1,2,3],[3,4,5],[6,7,8]]
lst2d

[[1, 2, 3], [3, 4, 5], [6, 7, 8]]

In [41]:
arr2d = np.array(lst2d)
arr2d

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
arr2d.shape

(3, 3)

In [43]:
arr2d.ndim

2

In [45]:
arr2d = np.arange(36).reshape(12,3)
arr2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35]])

In [131]:
arr2d = np.arange(36).reshape(6,6)
arr2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [47]:
arr2d.shape

(6, 6)

In [48]:
arr2d.ndim

2

In [5]:
list_prac = [[1,2,3],[4,5,7,8],[6,7,8]]

In [6]:
arr4d = np.array(list_prac)
arr4d

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [17]:
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr1d[7]


8

In [20]:
arr1d[4:8]

array([5, 6, 7, 8])

In [21]:
arr1d[-1]

10

In [23]:
arr1d[4:2]

array([], dtype=int32)

In [25]:
arr2d[2,5]

17

In [29]:
arr2d[2][5]

17

In [78]:
arr2_d = np.arange(36).reshape(4,9)
arr2_d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [35]:
arr2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [39]:
# in slice of 2d array we have two [row, col]
arr2d[1:2,2:6]

array([[ 8,  9, 10, 11]])

In [42]:
arr2d[2:4,2:4]

array([[14, 15],
       [20, 21]])

In [45]:
arr2d[0:6,3:6]

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23],
       [27, 28, 29],
       [33, 34, 35]])

In [46]:
arr2d[:6,3:]

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23],
       [27, 28, 29],
       [33, 34, 35]])

In [79]:
arr2_d[2,4:7]

array([22, 23, 24])

In [80]:
arr2_d[:,2]

array([ 2, 11, 20, 29])

In [60]:
arr3d[:,-1].shape

(4,)

In [61]:
arr3d[:,8:].shape

(4, 1)

In [57]:
arr3d.shape

(4, 9)

In [62]:
np.arange(10).reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [63]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.array(19).ndim

0

In [65]:
np.array([[[19]]]).ndim

3

# fancy indexing


In [81]:
arr2_d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [82]:
arr2_d[:,[5,8,0,3]]

array([[ 5,  8,  0,  3],
       [14, 17,  9, 12],
       [23, 26, 18, 21],
       [32, 35, 27, 30]])

In [73]:
arr2_d[[0,2],[2,7]]

array([ 2, 25])

In [74]:
arr2_d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [84]:
arr2_d[:,::2]

SyntaxError: invalid decimal literal (1999717254.py, line 1)

In [83]:
arr2_d[:,::-2]

array([[ 8,  6,  4,  2,  0],
       [17, 15, 13, 11,  9],
       [26, 24, 22, 20, 18],
       [35, 33, 31, 29, 27]])

In [86]:
#depth, raw, column
arr3d=np.arange(64).reshape(4,4,4)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [103]:
arr3d[:,2:3,1:3]

array([[[ 9, 10]],

       [[25, 26]],

       [[41, 42]],

       [[57, 58]]])

In [104]:
arr3d[::2,1:3]

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43]]])

In [106]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [112]:
np.zeros([4,5], dtype ="int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [108]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [110]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [115]:
np.ones([5,5])*10

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [116]:
np.ones([5,5])*5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [114]:
np.eye(10,dtype="int")

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [117]:
arr2_d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [118]:
arr2_d.T

array([[ 0,  9, 18, 27],
       [ 1, 10, 19, 28],
       [ 2, 11, 20, 29],
       [ 3, 12, 21, 30],
       [ 4, 13, 22, 31],
       [ 5, 14, 23, 32],
       [ 6, 15, 24, 33],
       [ 7, 16, 25, 34],
       [ 8, 17, 26, 35]])

In [121]:
arr2d2=arr2d
arr2d2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [135]:
arr2d2= np.random.randn(6,6)
arr2d2

array([[-1.49944593,  0.7080864 ,  0.34785222, -0.75606702, -1.13533565,
        -1.59728843],
       [ 0.48738061,  1.12736419,  0.77942011, -0.06192057, -1.06340831,
        -0.13854065],
       [ 0.78134737, -0.27489737, -0.12972782,  0.17793169, -0.43158553,
         0.04394502],
       [ 0.06073859,  0.82405903,  1.38728538,  1.24869454, -0.40641124,
         0.27327675],
       [-0.28768588,  0.11419624,  0.57548047,  0.15196768, -1.23389953,
         0.7730104 ],
       [ 1.62634561,  0.04170678,  0.25644517,  1.20637725,  0.69595935,
        -0.10899025]])

In [133]:
arr2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [136]:
arr2d2+arr2d

array([[-1.49944593,  1.7080864 ,  2.34785222,  2.24393298,  2.86466435,
         3.40271157],
       [ 6.48738061,  8.12736419,  8.77942011,  8.93807943,  8.93659169,
        10.86145935],
       [12.78134737, 12.72510263, 13.87027218, 15.17793169, 15.56841447,
        17.04394502],
       [18.06073859, 19.82405903, 21.38728538, 22.24869454, 21.59358876,
        23.27327675],
       [23.71231412, 25.11419624, 26.57548047, 27.15196768, 26.76610047,
        29.7730104 ],
       [31.62634561, 31.04170678, 32.25644517, 34.20637725, 34.69595935,
        34.89100975]])

In [140]:
a =np.arange(6).reshape(3,2)
b =np.arange(6).reshape(2,3)

In [141]:
a+b

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [142]:
b*a

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [143]:
a*b

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [146]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [147]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [144]:
b@a

array([[10, 13],
       [28, 40]])

In [145]:
a@b

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])

In [148]:
a.dot(b)

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])

In [149]:
b.dot(a)

array([[10, 13],
       [28, 40]])

In [150]:
np.linspace (1,100,50)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [153]:
np.linspace (1,100,100)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [157]:
np.linspace (1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [158]:
np.linspace (1,100,25)

array([  1.   ,   5.125,   9.25 ,  13.375,  17.5  ,  21.625,  25.75 ,
        29.875,  34.   ,  38.125,  42.25 ,  46.375,  50.5  ,  54.625,
        58.75 ,  62.875,  67.   ,  71.125,  75.25 ,  79.375,  83.5  ,
        87.625,  91.75 ,  95.875, 100.   ])

In [159]:
a.shape,a.dtype

((3, 2), dtype('int32'))

In [161]:
np.zeros_like(a)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [162]:
np.ones_like(a)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [164]:
# Boolean Slection filter/query

arr1d>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [166]:
#  can explain the how many true status is received
(arr1d>5).sum()

5

In [176]:
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [177]:
a = [True, False, True, False, False, True, True, False, True, False]


In [180]:
arr1d[a]

array([1, 3, 6, 7, 9])

In [181]:
arr1d[arr1d>5]

array([ 6,  7,  8,  9, 10])

In [183]:
arr1d[arr1d==5]

array([5])

In [187]:
arr1d[arr1d%2 !=0]

array([1, 3, 5, 7, 9])

In [188]:
arr2d>10

array([[False, False, False, False, False, False],
       [False, False, False, False, False,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [189]:
arr2d[arr2d>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35])

In [193]:

arr2d[(arr2d>10) & (arr2d<30)]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29])

In [194]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [207]:
# use for flat the data or 1D data
new3darray_a = arr3d.ravel()


In [206]:
new_arra3d_b= arr3d.flatten()

In [208]:
new_array3dc= arr3d.reshape(64)

In [205]:
new_array3dc= arr3d.reshape(64)

In [209]:
new3darray_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [239]:
new_arra3d_b[3:4] = 40

In [240]:
new_arra3d_b

array([ 0,  1,  2, 40,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [241]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [255]:
new3darray_a[3:4] = 40

In [256]:
new3darray_a

array([ 0,  1,  2, 40,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [212]:
new_array3dc


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [257]:
arr3d

array([[[ 0,  1,  2, 40],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [216]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [218]:
arr2d1=arr2d[:]*5

In [219]:
arr2d1

array([[  0,   5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50,  55],
       [ 60,  65,  70,  75,  80,  85],
       [ 90,  95, 100, 105, 110, 115],
       [120, 125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170, 175]])

In [220]:
new2d = np.concatenate([arr2d1,arr2d], axis=0)

In [221]:
new2d

array([[  0,   5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50,  55],
       [ 60,  65,  70,  75,  80,  85],
       [ 90,  95, 100, 105, 110, 115],
       [120, 125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170, 175],
       [  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35]])

In [223]:
new2d = np.concatenate([arr2d1,arr2d], axis=1)

In [224]:
new2d

array([[  0,   5,  10,  15,  20,  25,   0,   1,   2,   3,   4,   5],
       [ 30,  35,  40,  45,  50,  55,   6,   7,   8,   9,  10,  11],
       [ 60,  65,  70,  75,  80,  85,  12,  13,  14,  15,  16,  17],
       [ 90,  95, 100, 105, 110, 115,  18,  19,  20,  21,  22,  23],
       [120, 125, 130, 135, 140, 145,  24,  25,  26,  27,  28,  29],
       [150, 155, 160, 165, 170, 175,  30,  31,  32,  33,  34,  35]])

In [226]:
new2d= np.vstack((arr2d1,arr2d1)newne)

In [227]:
new2d

array([[  0,   5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50,  55],
       [ 60,  65,  70,  75,  80,  85],
       [ 90,  95, 100, 105, 110, 115],
       [120, 125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170, 175],
       [  0,   5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50,  55],
       [ 60,  65,  70,  75,  80,  85],
       [ 90,  95, 100, 105, 110, 115],
       [120, 125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170, 175]])

In [229]:
new2d= np.hstack((arr2d1,arr2d1))

In [230]:
new2d

array([[  0,   5,  10,  15,  20,  25,   0,   5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50,  55,  30,  35,  40,  45,  50,  55],
       [ 60,  65,  70,  75,  80,  85,  60,  65,  70,  75,  80,  85],
       [ 90,  95, 100, 105, 110, 115,  90,  95, 100, 105, 110, 115],
       [120, 125, 130, 135, 140, 145, 120, 125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170, 175, 150, 155, 160, 165, 170, 175]])

In [232]:
a = np.arange(9).reshape(3,3)
b= np.arange(10,19).reshape (3,3)

In [233]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [234]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [235]:
dstack = np.dstack((a,b))

In [236]:
dstack

array([[[ 0, 10],
        [ 1, 11],
        [ 2, 12]],

       [[ 3, 13],
        [ 4, 14],
        [ 5, 15]],

       [[ 6, 16],
        [ 7, 17],
        [ 8, 18]]])

In [243]:
arr2_d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [248]:
np.split(arr2_d,2,axis=0)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
        [27, 28, 29, 30, 31, 32, 33, 34, 35]])]

In [252]:
np.split(arr2_d,4,axis=0)

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([[27, 28, 29, 30, 31, 32, 33, 34, 35]])]

In [253]:
np.split(arr2_d,3,axis=0)

ValueError: array split does not result in an equal division

# broadcasting

In [271]:
x =np.arange(12).reshape(4,3)
y =np.arange(3)

In [268]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [275]:
z = x+y

In [276]:
z

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [272]:
x*y

array([[ 0,  1,  4],
       [ 0,  4, 10],
       [ 0,  7, 16],
       [ 0, 10, 22]])

In [278]:
np.broadcast()

In [ ]:
g = np.array([1],[2],[3])

# Pandas

In [281]:
import pandas as pd

In [294]:
s1 = pd.Series(['Nasir','umer', 'shahzad' ,'farhan', 'Umer'])

In [284]:
s1

0      Nasir
1       umer
2    shahzad
3     farhan
dtype: object

In [285]:
s1[2]

'shahzad'

In [286]:
s1[1]

'umer'

In [287]:
type(s1)

pandas.core.series.Series

In [289]:
s1[3] = "Farhana"
s1

0      Nasir
1       umer
2    shahzad
3    Farhana
dtype: object

In [290]:
s1[2:3]

2    shahzad
dtype: object

In [292]:
s1[[2,0]]

2    shahzad
0      Nasir
dtype: object

In [295]:
s1[s1=='umer']

1    umer
dtype: object

In [297]:
s2 =pd.Series([12,24,36,12,6,12,24], index=['apple', 'oranges','bananas', 'samosa', 'colddrink','chicken','roll'])

In [298]:
s2

apple        12
oranges      24
bananas      36
samosa       12
colddrink     6
chicken      12
roll         24
dtype: int64

In [303]:
s2['oranges':'roll']

oranges      24
bananas      36
samosa       12
colddrink     6
chicken      12
roll         24
dtype: int64

In [304]:
s3 =pd.Series([12,24,36,12,6,12,24], index=[0,1,2,3,4,5,6])

In [305]:
s3

0    12
1    24
2    36
3    12
4     6
5    12
6    24
dtype: int64

In [306]:
s3[3:5]

3    12
4     6
dtype: int64

In [307]:
# for integer loc
# for customised = iloc
s3.loc[3:5]

3    12
4     6
5    12
dtype: int64

In [308]:
s3.iloc[3:5]

3    12
4     6
dtype: int64

In [310]:
s2[3:6]

samosa       12
colddrink     6
chicken      12
dtype: int64

In [311]:
s2.loc['bananas':'colddrink']

bananas      36
samosa       12
colddrink     6
dtype: int64

In [312]:
s5 =pd.Series([13,24,36,15,6,12,24], index=[0,1,2,3,4,5,6])

In [313]:
s5

0    13
1    24
2    36
3    15
4     6
5    12
6    24
dtype: int64

In [314]:
s5[0:3]


0    13
1    24
2    36
dtype: int64

In [315]:
s5.loc[0:3]

0    13
1    24
2    36
3    15
dtype: int64

In [316]:
s5.iloc[0:3]

0    13
1    24
2    36
dtype: int64

In [317]:
# NAN= float always
s3+s2

0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
5           NaN
6           NaN
apple       NaN
bananas     NaN
chicken     NaN
colddrink   NaN
oranges     NaN
roll        NaN
samosa      NaN
dtype: float64

# Alignment

In [322]:
x1 = pd.Series ([1,2,3,4], dtype='int')

In [320]:
x1

0    1
1    2
2    3
3    4
dtype: int32

In [328]:
x2 = pd.Series([np.nan], index=[4])
x2

4   NaN
dtype: float64

x1.pandas.concat(x2)

In [326]:
x2

4   NaN
dtype: float64